"""
DogStrike Hero Spritesheet Assembler
=====================================
Assembles 11 individual frame PNGs (generated by ComfyUI) into a single
horizontal sprite sheet per hero character.

Expected input files in tools/generated/:
  <hero>_idle_a.png   frame 0
  <hero>_idle_b.png   frame 1
  <hero>_walk_a.png   frame 2
  <hero>_walk_b.png   frame 3
  <hero>_walk_c.png   frame 4
  <hero>_walk_d.png   frame 5
  <hero>_jump.png     frame 6
  <hero>_strike.png   frame 7
  <hero>_special_a.png  frame 8  (windup)
  <hero>_special_b.png  frame 9  (peak / howl / bark / glow)
  <hero>_special_c.png  frame 10 (release)

Output: ../assets/dogs/hero_<hero>_sheet.png  (1408 × 160 px, RGBA)

Usage:
  cd tools
  pip install pillow
  python assemble_sheet.py
"""

from PIL import Image
import os, sys

FRAME_W   = 128
FRAME_H   = 160
FRAME_SEQ = [
    'idle_a', 'idle_b',
    'walk_a', 'walk_b', 'walk_c', 'walk_d',
    'jump',
    'strike',
    'special_a', 'special_b', 'special_c',
]

HEROES = ['saint', 'shepherd', 'dachshund']

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
GEN_DIR     = os.path.join(SCRIPT_DIR, 'generated')
ASSETS_DIR  = os.path.join(SCRIPT_DIR, '..', 'assets', 'dogs')


def assemble(hero: str) -> None:
    n = len(FRAME_SEQ)
    sheet = Image.new('RGBA', (FRAME_W * n, FRAME_H), (0, 0, 0, 0))
    missing = []

    for i, frame_name in enumerate(FRAME_SEQ):
        path = os.path.join(GEN_DIR, f'{hero}_{frame_name}.png')
        if not os.path.exists(path):
            missing.append(frame_name)
            # Leave this slot transparent so the sheet can still be used partially
            continue
        img = Image.open(path).convert('RGBA')
        # Resize to exact frame dimensions (preserves aspect with letterboxing if needed)
        img.thumbnail((FRAME_W, FRAME_H), Image.LANCZOS)
        # Paste centered in the frame slot
        ox = (FRAME_W - img.width) // 2
        oy = (FRAME_H - img.height) // 2
        sheet.paste(img, (i * FRAME_W + ox, oy), img)

    out_path = os.path.join(ASSETS_DIR, f'hero_{hero}_sheet.png')
    sheet.save(out_path, 'PNG')
    status = f'OK ({n - len(missing)}/{n} frames)'
    if missing:
        status += f'  — MISSING: {", ".join(missing)}'
    print(f'  {hero:12s}  →  {out_path}  [{status}]')


if __name__ == '__main__':
    heroes = sys.argv[1:] if len(sys.argv) > 1 else HEROES
    print(f'Assembling sheets for: {", ".join(heroes)}')
    print(f'Source:  {GEN_DIR}')
    print(f'Output:  {ASSETS_DIR}')
    print()
    os.makedirs(ASSETS_DIR, exist_ok=True)
    for hero in heroes:
        assemble(hero)
    print('\nDone. Reload dogstrike.html to see the updated sprites.')
